//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekkenProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayStyle
    {
        public int ID { get; set; }
        public string Play_Style { get; set; }
        public string Difficulty { get; set; }
        public int CharactersID { get; set; }
    
        public virtual Characters Character { get; set; }
    }
}
